### ISSUE TITLE
binary not available

### ISSUE THREAD

**Issue by zenny** [booktype/booktype-packaging#2]
Hi,

Trying to install booktype binaries in debian9 stretch as described at https://sourcefabric.booktype.pro/booktype-24-for-authors-and-publishers/automated-install-on-debian-or-ubuntu-gnulinux/
```

# apt-key add sourcefabric-key
key 0888FE5B174C1854:                                                                                                                                                                          1 signature not checked due to a missing key                                                                                                                                                   
OK       

#apt upgrade
...

# apt-key add sourcefabric-key
OK      

~# apt update
Ign:1 http://ftp.debian.org/debian stretch InRelease
Hit:2 http://ftp.debian.org/debian stretch-updates InRelease
Hit:3 http://ftp.debian.org/debian stretch Release                                    
Hit:4 https://packages.sury.org/php stretch InRelease                                 
Hit:5 http://apt.postgresql.org/pub/repos/apt stretch-pgdg InRelease            
Hit:6 https://apt.sourcefabric.org stretch InRelease
Hit:8 http://security.debian.org stretch/updates InRelease              
Reading package lists... Done                                           
Building dependency tree       
Reading state information... Done
All packages are up to date.

~# apt search booktype
Sorting... Done
Full Text Search... Done
```
No package called 'booktype' found!!! What 

Cheers,
/z

**Comment by zenny** [comment]
Hi again,

I pulled http://apt.sourcefabric.org/snapshots/booktype_2.4.0~20190703-1_all.deb and installed gdebi to install all dependencies which ended up with:

```
# gdebi booktype_2.4.0~20190703-1_all.deb
....
*** Finishing default instance creation ***
/var/lib/dpkg/info/booktype.postinst: line 208: ./manage.py: No such file or directory
dpkg: error processing package booktype (--install):
 subprocess installed post-installation script returned error exit status 127
Processing triggers for man-db (2.7.6.1-2) ...
Errors were encountered while processing:
 booktype
```
Any inputs?

**Comment by zenny** [comment]
On searching the apache error log, it was due to the permission issue with the log files in booktype instances. However, fixing permission level gave partial page with 'Error 500\n Server Error'. But checking apache2 error logs do not point to any debugging leads. Any inputs?

Host specification matches what has been specified in the apache vhost.conf file. So it has nothing to do with host name mismatch.

UPDATE: The error resembles exactly like described here: https://forum.sourcefabric.org/discussion/18151/booktype-on-windows-10-using-oracle-vm-virtual-box/p1

However, doing something below (all as root) as suggested by @danielhjames at https://forum.sourcefabric.org/discussion/comment/34903#Comment_34903 didn't help either:

```
mkdir /usr/local/src/booktype
cd /usr/local/src/booktype
git fetch origin
git checkout master
git pull origin master
virtualenv venv
source venv/bin/activate
easy_install -U setuptools
pip install -r /usr/local/src/booktype/requirements/dev.txt
pip install -r /usr/local/src/booktype/requirements/prod.txt
supervisorctl restart all
service apache2 restart
```
No clue in the error logs again. Tried to upgrade the booktype binary from http://apt.sourcefabric.org/snapshots/booktype_2.4.0~20190704-1_all.deb, yet no changes. :(

Where is the missing link?

**Comment by danielhjames** [comment]
Hi @zenny I no longer work on Booktype, and I'm not aware that anyone is maintaining the Debian package. You might find an answer at https://forum.sourcefabric.org/categories/booktype-support

**Comment by zenny** [comment]
@danielhjames Thanks for your pointer.

I deployed manually which works with some tweaks, obviously.
